[2014-04-14 07:52:17] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined function Controllers\Admin\strtorime()' in /var/www/arp_dev/app/controllers/admin/DashboardController.php:69 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 08:03:16] log.ERROR: exception 'ErrorException' with message 'Undefined variable: payments' in /var/www/arp_dev/app/storage/views/cc228d75f3c20261dd87044a69c2c373:63 Stack trace: #0 /var/www/arp_dev/app/storage/views/cc228d75f3c20261dd87044a69c2c373(63): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/var/www/arp_de...', 63, Array) #1 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(38): include('/var/www/arp_de...') #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/arp_de...', Array) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/View/View.php(100): Illuminate\View\Engines\CompilerEngine->get('/var/www/arp_de...', Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/View/View.php(81): Illuminate\View\View->getContents() #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Http/Response.php(70): Illuminate\View\View->render() #6 /var/www/arp_dev/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(141): Illuminate\Http\Response->setContent(Object(Illuminate\View\View)) #7 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1414): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View)) #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request)) #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'getIndex', Object(Illuminate\View\View)) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #12 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #13 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #14 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #15 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #16 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #17 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #18 {main} [] []
[2014-04-14 08:16:03] log.ERROR: exception 'PDOException' with message 'SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: timestamp without time zone >= integer LINE 5:                   WHERE "order".datetimecreated >= 2014-04-0...                                                         ^ HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.' in /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php:274 Stack trace: #0 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(274): PDOStatement->execute(Array) #1 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\PostgresConnection), Object(Illuminate\Database\Query\Expression), Array) #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(277): Illuminate\Database\Connection->run(Object(Illuminate\Database\Query\Expression), Array, Object(Closure)) #3 [internal function]: Illuminate\Database\Connection->select(Object(Illuminate\Database\Query\Expression)) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(242): call_user_func_array(Array, Array) #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(206): Illuminate\Database\DatabaseManager->__call('select', Array) #6 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(206): Illuminate\Database\DatabaseManager->select(Object(Illuminate\Database\Query\Expression)) #7 /var/www/arp_dev/app/controllers/admin/DashboardController.php(132): Illuminate\Support\Facades\Facade::__callStatic('select', Array) #8 /var/www/arp_dev/app/controllers/admin/DashboardController.php(132): Illuminate\Support\Facades\DB::select(Object(Illuminate\Database\Query\Expression)) #9 /var/www/arp_dev/app/controllers/admin/DashboardController.php(76): Controllers\Admin\DashboardController->getTransactions('2014-04-04', '2014-04-14') #10 [internal function]: Controllers\Admin\DashboardController->getIndex() #11 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #12 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #13 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #14 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #15 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #16 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #17 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #18 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #19 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #20 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #21 {main} Next exception 'Exception' with message 'SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: timestamp without time zone >= integer LINE 5:                   WHERE "order".datetimecreated >= 2014-04-0...                                                         ^ HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts. (SQL: SELECT merchantagreement.name, COUNT("order".id) as totalTransaction FROM "order"                   JOIN transaction ON transaction.id = "order".transaction_id                   JOIN merchant ON merchant.id = transaction.merchant_id                   JOIN merchantagreement ON merchantagreement.merchant_id = merchant.id                   WHERE "order".datetimecreated >= 2014-04-04                   AND "order".datetimecreated <= 2014-04-14                   GROUP BY merchantagreement.id) (Bindings: array ( ))' in /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php:556 Stack trace: #0 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), Object(Illuminate\Database\Query\Expression), Array) #1 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(277): Illuminate\Database\Connection->run(Object(Illuminate\Database\Query\Expression), Array, Object(Closure)) #2 [internal function]: Illuminate\Database\Connection->select(Object(Illuminate\Database\Query\Expression)) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(242): call_user_func_array(Array, Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(206): Illuminate\Database\DatabaseManager->__call('select', Array) #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(206): Illuminate\Database\DatabaseManager->select(Object(Illuminate\Database\Query\Expression)) #6 /var/www/arp_dev/app/controllers/admin/DashboardController.php(132): Illuminate\Support\Facades\Facade::__callStatic('select', Array) #7 /var/www/arp_dev/app/controllers/admin/DashboardController.php(132): Illuminate\Support\Facades\DB::select(Object(Illuminate\Database\Query\Expression)) #8 /var/www/arp_dev/app/controllers/admin/DashboardController.php(76): Controllers\Admin\DashboardController->getTransactions('2014-04-04', '2014-04-14') #9 [internal function]: Controllers\Admin\DashboardController->getIndex() #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #11 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #12 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #13 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #14 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #15 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #16 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #17 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #18 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #19 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #20 {main} [] []
[2014-04-14 08:17:29] log.ERROR: exception 'PDOException' with message 'SQLSTATE[42703]: Undefined column: 7 ERROR:  column "2014-04-04 00:00:00" does not exist LINE 5: ...                 WHERE "order".datetimecreated >= "2014-04-0...                                                              ^' in /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php:274 Stack trace: #0 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(274): PDOStatement->execute(Array) #1 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\PostgresConnection), Object(Illuminate\Database\Query\Expression), Array) #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(277): Illuminate\Database\Connection->run(Object(Illuminate\Database\Query\Expression), Array, Object(Closure)) #3 [internal function]: Illuminate\Database\Connection->select(Object(Illuminate\Database\Query\Expression)) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(242): call_user_func_array(Array, Array) #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(206): Illuminate\Database\DatabaseManager->__call('select', Array) #6 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(206): Illuminate\Database\DatabaseManager->select(Object(Illuminate\Database\Query\Expression)) #7 /var/www/arp_dev/app/controllers/admin/DashboardController.php(132): Illuminate\Support\Facades\Facade::__callStatic('select', Array) #8 /var/www/arp_dev/app/controllers/admin/DashboardController.php(132): Illuminate\Support\Facades\DB::select(Object(Illuminate\Database\Query\Expression)) #9 /var/www/arp_dev/app/controllers/admin/DashboardController.php(76): Controllers\Admin\DashboardController->getTransactions('2014-04-04', '2014-04-14') #10 [internal function]: Controllers\Admin\DashboardController->getIndex() #11 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #12 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #13 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #14 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #15 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #16 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #17 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #18 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #19 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #20 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #21 {main} Next exception 'Exception' with message 'SQLSTATE[42703]: Undefined column: 7 ERROR:  column "2014-04-04 00:00:00" does not exist LINE 5: ...                 WHERE "order".datetimecreated >= "2014-04-0...                                                              ^ (SQL: SELECT merchantagreement.name, COUNT("order".id) as totalTransaction FROM "order"                   JOIN transaction ON transaction.id = "order".transaction_id                   JOIN merchant ON merchant.id = transaction.merchant_id                   JOIN merchantagreement ON merchantagreement.merchant_id = merchant.id                   WHERE "order".datetimecreated >= "2014-04-04 00:00:00"                   AND "order".datetimecreated <= "2014-04-14 00:00:00"                   GROUP BY merchantagreement.id) (Bindings: array ( ))' in /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php:556 Stack trace: #0 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), Object(Illuminate\Database\Query\Expression), Array) #1 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(277): Illuminate\Database\Connection->run(Object(Illuminate\Database\Query\Expression), Array, Object(Closure)) #2 [internal function]: Illuminate\Database\Connection->select(Object(Illuminate\Database\Query\Expression)) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(242): call_user_func_array(Array, Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(206): Illuminate\Database\DatabaseManager->__call('select', Array) #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(206): Illuminate\Database\DatabaseManager->select(Object(Illuminate\Database\Query\Expression)) #6 /var/www/arp_dev/app/controllers/admin/DashboardController.php(132): Illuminate\Support\Facades\Facade::__callStatic('select', Array) #7 /var/www/arp_dev/app/controllers/admin/DashboardController.php(132): Illuminate\Support\Facades\DB::select(Object(Illuminate\Database\Query\Expression)) #8 /var/www/arp_dev/app/controllers/admin/DashboardController.php(76): Controllers\Admin\DashboardController->getTransactions('2014-04-04', '2014-04-14') #9 [internal function]: Controllers\Admin\DashboardController->getIndex() #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #11 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #12 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #13 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #14 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #15 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #16 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #17 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #18 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #19 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #20 {main} [] []
[2014-04-14 08:17:43] log.ERROR: exception 'PDOException' with message 'SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: timestamp without time zone >= integer LINE 5:                   WHERE "order".datetimecreated >= 2014-04-0...                                                         ^ HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.' in /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php:274 Stack trace: #0 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(274): PDOStatement->execute(Array) #1 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\PostgresConnection), Object(Illuminate\Database\Query\Expression), Array) #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(277): Illuminate\Database\Connection->run(Object(Illuminate\Database\Query\Expression), Array, Object(Closure)) #3 [internal function]: Illuminate\Database\Connection->select(Object(Illuminate\Database\Query\Expression)) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(242): call_user_func_array(Array, Array) #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(206): Illuminate\Database\DatabaseManager->__call('select', Array) #6 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(206): Illuminate\Database\DatabaseManager->select(Object(Illuminate\Database\Query\Expression)) #7 /var/www/arp_dev/app/controllers/admin/DashboardController.php(132): Illuminate\Support\Facades\Facade::__callStatic('select', Array) #8 /var/www/arp_dev/app/controllers/admin/DashboardController.php(132): Illuminate\Support\Facades\DB::select(Object(Illuminate\Database\Query\Expression)) #9 /var/www/arp_dev/app/controllers/admin/DashboardController.php(76): Controllers\Admin\DashboardController->getTransactions('2014-04-04', '2014-04-14') #10 [internal function]: Controllers\Admin\DashboardController->getIndex() #11 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #12 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #13 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #14 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #15 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #16 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #17 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #18 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #19 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #20 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #21 {main} Next exception 'Exception' with message 'SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: timestamp without time zone >= integer LINE 5:                   WHERE "order".datetimecreated >= 2014-04-0...                                                         ^ HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts. (SQL: SELECT merchantagreement.name, COUNT("order".id) as totalTransaction FROM "order"                   JOIN transaction ON transaction.id = "order".transaction_id                   JOIN merchant ON merchant.id = transaction.merchant_id                   JOIN merchantagreement ON merchantagreement.merchant_id = merchant.id                   WHERE "order".datetimecreated >= 2014-04-04                   AND "order".datetimecreated <= 2014-04-14                   GROUP BY merchantagreement.id) (Bindings: array ( ))' in /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php:556 Stack trace: #0 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), Object(Illuminate\Database\Query\Expression), Array) #1 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(277): Illuminate\Database\Connection->run(Object(Illuminate\Database\Query\Expression), Array, Object(Closure)) #2 [internal function]: Illuminate\Database\Connection->select(Object(Illuminate\Database\Query\Expression)) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(242): call_user_func_array(Array, Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(206): Illuminate\Database\DatabaseManager->__call('select', Array) #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(206): Illuminate\Database\DatabaseManager->select(Object(Illuminate\Database\Query\Expression)) #6 /var/www/arp_dev/app/controllers/admin/DashboardController.php(132): Illuminate\Support\Facades\Facade::__callStatic('select', Array) #7 /var/www/arp_dev/app/controllers/admin/DashboardController.php(132): Illuminate\Support\Facades\DB::select(Object(Illuminate\Database\Query\Expression)) #8 /var/www/arp_dev/app/controllers/admin/DashboardController.php(76): Controllers\Admin\DashboardController->getTransactions('2014-04-04', '2014-04-14') #9 [internal function]: Controllers\Admin\DashboardController->getIndex() #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #11 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #12 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #13 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #14 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #15 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #16 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #17 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #18 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #19 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #20 {main} [] []
[2014-04-14 08:20:01] log.ERROR: exception 'PDOException' with message 'SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: timestamp without time zone >= integer LINE 5:                   WHERE "order".datetimecreated >= 2014-04-0...                                                         ^ HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.' in /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php:274 Stack trace: #0 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(274): PDOStatement->execute(Array) #1 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\PostgresConnection), Object(Illuminate\Database\Query\Expression), Array) #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(277): Illuminate\Database\Connection->run(Object(Illuminate\Database\Query\Expression), Array, Object(Closure)) #3 [internal function]: Illuminate\Database\Connection->select(Object(Illuminate\Database\Query\Expression)) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(242): call_user_func_array(Array, Array) #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(206): Illuminate\Database\DatabaseManager->__call('select', Array) #6 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(206): Illuminate\Database\DatabaseManager->select(Object(Illuminate\Database\Query\Expression)) #7 /var/www/arp_dev/app/controllers/admin/DashboardController.php(131): Illuminate\Support\Facades\Facade::__callStatic('select', Array) #8 /var/www/arp_dev/app/controllers/admin/DashboardController.php(131): Illuminate\Support\Facades\DB::select(Object(Illuminate\Database\Query\Expression)) #9 /var/www/arp_dev/app/controllers/admin/DashboardController.php(75): Controllers\Admin\DashboardController->getTransactions('2014-04-04', '2014-04-14') #10 [internal function]: Controllers\Admin\DashboardController->getIndex() #11 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #12 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #13 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #14 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #15 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #16 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #17 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #18 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #19 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #20 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #21 {main} Next exception 'Exception' with message 'SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: timestamp without time zone >= integer LINE 5:                   WHERE "order".datetimecreated >= 2014-04-0...                                                         ^ HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts. (SQL: SELECT merchantagreement.name, COUNT("order".id) as totalTransaction FROM "order"                   JOIN transaction ON transaction.id = "order".transaction_id                   JOIN merchant ON merchant.id = transaction.merchant_id                   JOIN merchantagreement ON merchantagreement.merchant_id = merchant.id                   WHERE "order".datetimecreated >= 2014-04-04                   AND "order".datetimecreated <= 2014-04-14                   GROUP BY merchantagreement.id) (Bindings: array ( ))' in /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php:556 Stack trace: #0 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), Object(Illuminate\Database\Query\Expression), Array) #1 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(277): Illuminate\Database\Connection->run(Object(Illuminate\Database\Query\Expression), Array, Object(Closure)) #2 [internal function]: Illuminate\Database\Connection->select(Object(Illuminate\Database\Query\Expression)) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(242): call_user_func_array(Array, Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(206): Illuminate\Database\DatabaseManager->__call('select', Array) #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(206): Illuminate\Database\DatabaseManager->select(Object(Illuminate\Database\Query\Expression)) #6 /var/www/arp_dev/app/controllers/admin/DashboardController.php(131): Illuminate\Support\Facades\Facade::__callStatic('select', Array) #7 /var/www/arp_dev/app/controllers/admin/DashboardController.php(131): Illuminate\Support\Facades\DB::select(Object(Illuminate\Database\Query\Expression)) #8 /var/www/arp_dev/app/controllers/admin/DashboardController.php(75): Controllers\Admin\DashboardController->getTransactions('2014-04-04', '2014-04-14') #9 [internal function]: Controllers\Admin\DashboardController->getIndex() #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #11 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #12 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #13 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #14 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #15 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #16 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #17 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #18 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #19 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #20 {main} [] []
[2014-04-14 08:20:59] log.ERROR: exception 'PDOException' with message 'SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: timestamp without time zone >= integer LINE 5:                   WHERE "order".datetimecreated >= 2014-04-0...                                                         ^ HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.' in /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php:274 Stack trace: #0 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(274): PDOStatement->execute(Array) #1 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\PostgresConnection), Object(Illuminate\Database\Query\Expression), Array) #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(277): Illuminate\Database\Connection->run(Object(Illuminate\Database\Query\Expression), Array, Object(Closure)) #3 [internal function]: Illuminate\Database\Connection->select(Object(Illuminate\Database\Query\Expression)) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(242): call_user_func_array(Array, Array) #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(206): Illuminate\Database\DatabaseManager->__call('select', Array) #6 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(206): Illuminate\Database\DatabaseManager->select(Object(Illuminate\Database\Query\Expression)) #7 /var/www/arp_dev/app/controllers/admin/DashboardController.php(131): Illuminate\Support\Facades\Facade::__callStatic('select', Array) #8 /var/www/arp_dev/app/controllers/admin/DashboardController.php(131): Illuminate\Support\Facades\DB::select(Object(Illuminate\Database\Query\Expression)) #9 /var/www/arp_dev/app/controllers/admin/DashboardController.php(75): Controllers\Admin\DashboardController->getTransactions('2014-04-04', '2014-04-14') #10 [internal function]: Controllers\Admin\DashboardController->getIndex() #11 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #12 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #13 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #14 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #15 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #16 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #17 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #18 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #19 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #20 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #21 {main} Next exception 'Exception' with message 'SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: timestamp without time zone >= integer LINE 5:                   WHERE "order".datetimecreated >= 2014-04-0...                                                         ^ HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts. (SQL: SELECT merchantagreement.name, COUNT("order".id) as totalTransaction FROM "order"                   JOIN transaction ON transaction.id = "order".transaction_id                   JOIN merchant ON merchant.id = transaction.merchant_id                   JOIN merchantagreement ON merchantagreement.merchant_id = merchant.id                   WHERE "order".datetimecreated >= 2014-04-04                   AND "order".datetimecreated < 2014-04-14                   GROUP BY merchantagreement.id) (Bindings: array ( ))' in /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php:556 Stack trace: #0 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), Object(Illuminate\Database\Query\Expression), Array) #1 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(277): Illuminate\Database\Connection->run(Object(Illuminate\Database\Query\Expression), Array, Object(Closure)) #2 [internal function]: Illuminate\Database\Connection->select(Object(Illuminate\Database\Query\Expression)) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(242): call_user_func_array(Array, Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(206): Illuminate\Database\DatabaseManager->__call('select', Array) #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(206): Illuminate\Database\DatabaseManager->select(Object(Illuminate\Database\Query\Expression)) #6 /var/www/arp_dev/app/controllers/admin/DashboardController.php(131): Illuminate\Support\Facades\Facade::__callStatic('select', Array) #7 /var/www/arp_dev/app/controllers/admin/DashboardController.php(131): Illuminate\Support\Facades\DB::select(Object(Illuminate\Database\Query\Expression)) #8 /var/www/arp_dev/app/controllers/admin/DashboardController.php(75): Controllers\Admin\DashboardController->getTransactions('2014-04-04', '2014-04-14') #9 [internal function]: Controllers\Admin\DashboardController->getIndex() #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #11 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #12 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #13 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #14 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #15 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #16 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #17 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #18 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #19 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #20 {main} [] []
[2014-04-14 08:21:25] log.ERROR: exception 'PDOException' with message 'SQLSTATE[42703]: Undefined column: 7 ERROR:  column "2014-04-04" does not exist LINE 5: ...                 WHERE "order".datetimecreated >= "2014-04-0...                                                              ^' in /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php:274 Stack trace: #0 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(274): PDOStatement->execute(Array) #1 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\PostgresConnection), Object(Illuminate\Database\Query\Expression), Array) #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(277): Illuminate\Database\Connection->run(Object(Illuminate\Database\Query\Expression), Array, Object(Closure)) #3 [internal function]: Illuminate\Database\Connection->select(Object(Illuminate\Database\Query\Expression)) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(242): call_user_func_array(Array, Array) #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(206): Illuminate\Database\DatabaseManager->__call('select', Array) #6 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(206): Illuminate\Database\DatabaseManager->select(Object(Illuminate\Database\Query\Expression)) #7 /var/www/arp_dev/app/controllers/admin/DashboardController.php(131): Illuminate\Support\Facades\Facade::__callStatic('select', Array) #8 /var/www/arp_dev/app/controllers/admin/DashboardController.php(131): Illuminate\Support\Facades\DB::select(Object(Illuminate\Database\Query\Expression)) #9 /var/www/arp_dev/app/controllers/admin/DashboardController.php(75): Controllers\Admin\DashboardController->getTransactions('2014-04-04', '2014-04-14') #10 [internal function]: Controllers\Admin\DashboardController->getIndex() #11 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #12 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #13 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #14 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #15 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #16 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #17 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #18 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #19 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #20 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #21 {main} Next exception 'Exception' with message 'SQLSTATE[42703]: Undefined column: 7 ERROR:  column "2014-04-04" does not exist LINE 5: ...                 WHERE "order".datetimecreated >= "2014-04-0...                                                              ^ (SQL: SELECT merchantagreement.name, COUNT("order".id) as totalTransaction FROM "order"                   JOIN transaction ON transaction.id = "order".transaction_id                   JOIN merchant ON merchant.id = transaction.merchant_id                   JOIN merchantagreement ON merchantagreement.merchant_id = merchant.id                   WHERE "order".datetimecreated >= "2014-04-04"                   AND "order".datetimecreated < "2014-04-14"                   GROUP BY merchantagreement.id) (Bindings: array ( ))' in /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php:556 Stack trace: #0 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), Object(Illuminate\Database\Query\Expression), Array) #1 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(277): Illuminate\Database\Connection->run(Object(Illuminate\Database\Query\Expression), Array, Object(Closure)) #2 [internal function]: Illuminate\Database\Connection->select(Object(Illuminate\Database\Query\Expression)) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(242): call_user_func_array(Array, Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(206): Illuminate\Database\DatabaseManager->__call('select', Array) #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(206): Illuminate\Database\DatabaseManager->select(Object(Illuminate\Database\Query\Expression)) #6 /var/www/arp_dev/app/controllers/admin/DashboardController.php(131): Illuminate\Support\Facades\Facade::__callStatic('select', Array) #7 /var/www/arp_dev/app/controllers/admin/DashboardController.php(131): Illuminate\Support\Facades\DB::select(Object(Illuminate\Database\Query\Expression)) #8 /var/www/arp_dev/app/controllers/admin/DashboardController.php(75): Controllers\Admin\DashboardController->getTransactions('2014-04-04', '2014-04-14') #9 [internal function]: Controllers\Admin\DashboardController->getIndex() #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #11 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #12 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #13 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #14 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #15 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #16 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #17 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #18 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #19 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #20 {main} [] []
[2014-04-14 09:15:39] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Controllers\Admin\Lava' not found' in /var/www/arp_dev/app/controllers/admin/DashboardController.php:77 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 09:15:57] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 09:17:44] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 09:17:46] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 09:17:47] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 09:17:47] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 09:27:34] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 09:31:58] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 09:35:20] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 09:35:22] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 09:36:52] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 09:37:24] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 09:37:25] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 09:37:25] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 09:37:25] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 09:37:25] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 09:37:25] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 09:37:26] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 09:37:26] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 09:37:26] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 09:37:26] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 09:38:04] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 09:38:26] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 09:38:27] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 09:38:27] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 09:38:27] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 09:38:27] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 09:38:27] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 09:38:27] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 09:38:27] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 09:38:28] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 09:38:28] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 09:38:28] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 09:38:28] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 09:38:28] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 09:38:28] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 09:38:28] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 09:38:28] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 09:38:34] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 09:43:54] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 09:45:11] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 09:45:13] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 09:45:14] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 09:45:14] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 09:45:14] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 09:45:14] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 09:45:15] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 09:50:17] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 10:03:40] log.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in /var/www/arp_dev/app/controllers/admin/DashboardController.php:103 Stack trace: #0 /var/www/arp_dev/app/controllers/admin/DashboardController.php(103): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', '/var/www/arp_de...', 103, Array) #1 [internal function]: Controllers\Admin\DashboardController->getIndex() #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2014-04-14 10:04:25] log.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in /var/www/arp_dev/app/controllers/admin/DashboardController.php:103 Stack trace: #0 /var/www/arp_dev/app/controllers/admin/DashboardController.php(103): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', '/var/www/arp_de...', 103, Array) #1 [internal function]: Controllers\Admin\DashboardController->getIndex() #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2014-04-14 10:06:30] log.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in /var/www/arp_dev/app/controllers/admin/DashboardController.php:105 Stack trace: #0 /var/www/arp_dev/app/controllers/admin/DashboardController.php(105): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', '/var/www/arp_de...', 105, Array) #1 [internal function]: Controllers\Admin\DashboardController->getIndex() #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2014-04-14 10:09:18] log.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in /var/www/arp_dev/app/controllers/admin/DashboardController.php:105 Stack trace: #0 /var/www/arp_dev/app/controllers/admin/DashboardController.php(105): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', '/var/www/arp_de...', 105, Array) #1 [internal function]: Controllers\Admin\DashboardController->getIndex() #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2014-04-14 10:09:28] log.ERROR: exception 'ErrorException' with message 'Undefined index: name' in /var/www/arp_dev/app/controllers/admin/DashboardController.php:105 Stack trace: #0 /var/www/arp_dev/app/controllers/admin/DashboardController.php(105): Illuminate\Exception\Handler->handleError(8, 'Undefined index...', '/var/www/arp_de...', 105, Array) #1 [internal function]: Controllers\Admin\DashboardController->getIndex() #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2014-04-14 10:15:01] log.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in /var/www/arp_dev/app/controllers/admin/DashboardController.php:106 Stack trace: #0 /var/www/arp_dev/app/controllers/admin/DashboardController.php(106): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', '/var/www/arp_de...', 106, Array) #1 [internal function]: Controllers\Admin\DashboardController->getIndex() #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2014-04-14 10:15:09] log.ERROR: exception 'ErrorException' with message 'Undefined variable: data' in /var/www/arp_dev/app/controllers/admin/DashboardController.php:110 Stack trace: #0 /var/www/arp_dev/app/controllers/admin/DashboardController.php(110): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/var/www/arp_de...', 110, Array) #1 [internal function]: Controllers\Admin\DashboardController->getIndex() #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2014-04-14 10:23:21] log.ERROR: exception 'ErrorException' with message 'Use of undefined constant V - assumed 'V'' in /var/www/arp_dev/app/controllers/admin/DashboardController.php:105 Stack trace: #0 /var/www/arp_dev/app/controllers/admin/DashboardController.php(105): Illuminate\Exception\Handler->handleError(8, 'Use of undefine...', '/var/www/arp_de...', 105, Array) #1 [internal function]: Controllers\Admin\DashboardController->getIndex() #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2014-04-14 10:23:30] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 10:24:40] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 10:24:59] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 10:25:32] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 10:27:36] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 10:27:42] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 10:28:47] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 10:28:54] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 10:29:05] log.ERROR: exception 'ErrorException' with message 'Undefined variable: data' in /var/www/arp_dev/app/controllers/admin/DashboardController.php:113 Stack trace: #0 /var/www/arp_dev/app/controllers/admin/DashboardController.php(113): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/var/www/arp_de...', 113, Array) #1 [internal function]: Controllers\Admin\DashboardController->getIndex() #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2014-04-14 10:56:22] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 10:56:29] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 10:56:36] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 10:56:42] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Khill\Lavacharts\Configs\Lavacharts' not found' in /var/www/arp_dev/vendor/khill/lavacharts/src/Khill/Lavacharts/Configs/DataTable.php:476 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 11:08:29] log.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in /var/www/arp_dev/app/controllers/admin/DashboardController.php:105 Stack trace: #0 /var/www/arp_dev/app/controllers/admin/DashboardController.php(105): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', '/var/www/arp_de...', 105, Array) #1 [internal function]: Controllers\Admin\DashboardController->getIndex() #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2014-04-14 11:10:06] log.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in /var/www/arp_dev/app/controllers/admin/DashboardController.php:105 Stack trace: #0 /var/www/arp_dev/app/controllers/admin/DashboardController.php(105): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', '/var/www/arp_de...', 105, Array) #1 [internal function]: Controllers\Admin\DashboardController->getIndex() #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2014-04-14 11:10:15] log.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in /var/www/arp_dev/app/controllers/admin/DashboardController.php:107 Stack trace: #0 /var/www/arp_dev/app/controllers/admin/DashboardController.php(107): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', '/var/www/arp_de...', 107, Array) #1 [internal function]: Controllers\Admin\DashboardController->getIndex() #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2014-04-14 11:11:24] log.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in /var/www/arp_dev/app/controllers/admin/DashboardController.php:109 Stack trace: #0 /var/www/arp_dev/app/controllers/admin/DashboardController.php(109): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', '/var/www/arp_de...', 109, Array) #1 [internal function]: Controllers\Admin\DashboardController->getIndex() #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2014-04-14 11:29:00] log.ERROR: exception 'PDOException' with message 'SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near ")" LINE 6: ...r_event.event_id ="494" OR voucher_event.event_id ="495" OR)                                                                       ^' in /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php:274 Stack trace: #0 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(274): PDOStatement->execute(Array) #1 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\PostgresConnection), Object(Illuminate\Database\Query\Expression), Array) #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(277): Illuminate\Database\Connection->run(Object(Illuminate\Database\Query\Expression), Array, Object(Closure)) #3 [internal function]: Illuminate\Database\Connection->select(Object(Illuminate\Database\Query\Expression)) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(242): call_user_func_array(Array, Array) #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(206): Illuminate\Database\DatabaseManager->__call('select', Array) #6 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(206): Illuminate\Database\DatabaseManager->select(Object(Illuminate\Database\Query\Expression)) #7 /var/www/arp_dev/app/controllers/admin/DashboardController.php(265): Illuminate\Support\Facades\Facade::__callStatic('select', Array) #8 /var/www/arp_dev/app/controllers/admin/DashboardController.php(265): Illuminate\Support\Facades\DB::select(Object(Illuminate\Database\Query\Expression)) #9 /var/www/arp_dev/app/controllers/admin/DashboardController.php(105): Controllers\Admin\DashboardController->getChargebacks('2014-04-04', '2014-04-14') #10 [internal function]: Controllers\Admin\DashboardController->getIndex() #11 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #12 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #13 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #14 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #15 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #16 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #17 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #18 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #19 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #20 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #21 {main} Next exception 'Exception' with message 'SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near ")" LINE 6: ...r_event.event_id ="494" OR voucher_event.event_id ="495" OR)                                                                       ^ (SQL: SELECT merchantagreement.name, COUNT(voucher_event.id) as totalchb FROM voucher_event                   JOIN merchant ON merchant.id = voucher_event.merchant_id                   JOIN merchantagreement ON merchantagreement.merchant_id = merchant.id                   WHERE voucher_event.datetimecreated >= '2014-04-04'                   AND voucher_event.datetimecreated <= '2014-04-14'                   AND (voucher_event.event_id ="491" OR voucher_event.event_id ="492" OR voucher_event.event_id ="494" OR voucher_event.event_id ="495" OR)                   GROUP BY merchantagreement.id) (Bindings: array ( ))' in /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php:556 Stack trace: #0 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), Object(Illuminate\Database\Query\Expression), Array) #1 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(277): Illuminate\Database\Connection->run(Object(Illuminate\Database\Query\Expression), Array, Object(Closure)) #2 [internal function]: Illuminate\Database\Connection->select(Object(Illuminate\Database\Query\Expression)) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(242): call_user_func_array(Array, Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(206): Illuminate\Database\DatabaseManager->__call('select', Array) #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(206): Illuminate\Database\DatabaseManager->select(Object(Illuminate\Database\Query\Expression)) #6 /var/www/arp_dev/app/controllers/admin/DashboardController.php(265): Illuminate\Support\Facades\Facade::__callStatic('select', Array) #7 /var/www/arp_dev/app/controllers/admin/DashboardController.php(265): Illuminate\Support\Facades\DB::select(Object(Illuminate\Database\Query\Expression)) #8 /var/www/arp_dev/app/controllers/admin/DashboardController.php(105): Controllers\Admin\DashboardController->getChargebacks('2014-04-04', '2014-04-14') #9 [internal function]: Controllers\Admin\DashboardController->getIndex() #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #11 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #12 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #13 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #14 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #15 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #16 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #17 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #18 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #19 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #20 {main} [] []
[2014-04-14 11:29:54] log.ERROR: exception 'PDOException' with message 'SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near ")" LINE 6: ...r_event.event_id ="494" OR voucher_event.event_id ="495" OR)                                                                       ^' in /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php:274 Stack trace: #0 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(274): PDOStatement->execute(Array) #1 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\PostgresConnection), Object(Illuminate\Database\Query\Expression), Array) #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(277): Illuminate\Database\Connection->run(Object(Illuminate\Database\Query\Expression), Array, Object(Closure)) #3 [internal function]: Illuminate\Database\Connection->select(Object(Illuminate\Database\Query\Expression)) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(242): call_user_func_array(Array, Array) #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(206): Illuminate\Database\DatabaseManager->__call('select', Array) #6 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(206): Illuminate\Database\DatabaseManager->select(Object(Illuminate\Database\Query\Expression)) #7 /var/www/arp_dev/app/controllers/admin/DashboardController.php(265): Illuminate\Support\Facades\Facade::__callStatic('select', Array) #8 /var/www/arp_dev/app/controllers/admin/DashboardController.php(265): Illuminate\Support\Facades\DB::select(Object(Illuminate\Database\Query\Expression)) #9 /var/www/arp_dev/app/controllers/admin/DashboardController.php(105): Controllers\Admin\DashboardController->getChargebacks('2014-04-04', '2014-04-14') #10 [internal function]: Controllers\Admin\DashboardController->getIndex() #11 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #12 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #13 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #14 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #15 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #16 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #17 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #18 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #19 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #20 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #21 {main} Next exception 'Exception' with message 'SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near ")" LINE 6: ...r_event.event_id ="494" OR voucher_event.event_id ="495" OR)                                                                       ^ (SQL: SELECT merchantagreement.name, COUNT(voucher_event.id) as totalchb FROM voucher_event                   JOIN merchant ON merchant.id = voucher_event.merchant_id                   JOIN merchantagreement ON merchantagreement.merchant_id = merchant.id                   WHERE voucher_event.datetimecreated >= '2014-04-04'                   AND voucher_event.datetimecreated <= '2014-04-14'                   AND (voucher_event.event_id ="491" OR voucher_event.event_id ="492" OR voucher_event.event_id ="494" OR voucher_event.event_id ="495" OR)                   GROUP BY merchantagreement.id) (Bindings: array ( ))' in /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php:556 Stack trace: #0 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), Object(Illuminate\Database\Query\Expression), Array) #1 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(277): Illuminate\Database\Connection->run(Object(Illuminate\Database\Query\Expression), Array, Object(Closure)) #2 [internal function]: Illuminate\Database\Connection->select(Object(Illuminate\Database\Query\Expression)) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(242): call_user_func_array(Array, Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(206): Illuminate\Database\DatabaseManager->__call('select', Array) #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(206): Illuminate\Database\DatabaseManager->select(Object(Illuminate\Database\Query\Expression)) #6 /var/www/arp_dev/app/controllers/admin/DashboardController.php(265): Illuminate\Support\Facades\Facade::__callStatic('select', Array) #7 /var/www/arp_dev/app/controllers/admin/DashboardController.php(265): Illuminate\Support\Facades\DB::select(Object(Illuminate\Database\Query\Expression)) #8 /var/www/arp_dev/app/controllers/admin/DashboardController.php(105): Controllers\Admin\DashboardController->getChargebacks('2014-04-04', '2014-04-14') #9 [internal function]: Controllers\Admin\DashboardController->getIndex() #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #11 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #12 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #13 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #14 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #15 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #16 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #17 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #18 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #19 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #20 {main} [] []
[2014-04-14 11:31:54] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Controllers\Admin\Voucherevent' not found' in /var/www/arp_dev/app/controllers/admin/DashboardController.php:267 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 11:36:24] log.ERROR: exception 'ErrorException' with message 'Missing argument 3 for Controllers\Admin\DashboardController::getRefunds(), called in /var/www/arp_dev/app/controllers/admin/DashboardController.php on line 105 and defined' in /var/www/arp_dev/app/controllers/admin/DashboardController.php:242 Stack trace: #0 /var/www/arp_dev/app/controllers/admin/DashboardController.php(242): Illuminate\Exception\Handler->handleError(2, 'Missing argumen...', '/var/www/arp_de...', 242, Array) #1 /var/www/arp_dev/app/controllers/admin/DashboardController.php(105): Controllers\Admin\DashboardController->getRefunds('2014-04-04', '2014-04-14') #2 [internal function]: Controllers\Admin\DashboardController->getIndex() #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #7 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #11 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #12 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #13 {main} [] []
[2014-04-14 11:36:51] log.ERROR: exception 'PDOException' with message 'SQLSTATE[42703]: Undefined column: 7 ERROR:  column "490" does not exist LINE 6:                   AND voucher_event.event_id = "490"                                                        ^' in /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php:274 Stack trace: #0 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(274): PDOStatement->execute(Array) #1 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\PostgresConnection), Object(Illuminate\Database\Query\Expression), Array) #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(277): Illuminate\Database\Connection->run(Object(Illuminate\Database\Query\Expression), Array, Object(Closure)) #3 [internal function]: Illuminate\Database\Connection->select(Object(Illuminate\Database\Query\Expression)) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(242): call_user_func_array(Array, Array) #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(206): Illuminate\Database\DatabaseManager->__call('select', Array) #6 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(206): Illuminate\Database\DatabaseManager->select(Object(Illuminate\Database\Query\Expression)) #7 /var/www/arp_dev/app/controllers/admin/DashboardController.php(254): Illuminate\Support\Facades\Facade::__callStatic('select', Array) #8 /var/www/arp_dev/app/controllers/admin/DashboardController.php(254): Illuminate\Support\Facades\DB::select(Object(Illuminate\Database\Query\Expression)) #9 /var/www/arp_dev/app/controllers/admin/DashboardController.php(105): Controllers\Admin\DashboardController->getRefunds('2014-04-04', '2014-04-14') #10 [internal function]: Controllers\Admin\DashboardController->getIndex() #11 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #12 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #13 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #14 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #15 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #16 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #17 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #18 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #19 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #20 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #21 {main} Next exception 'Exception' with message 'SQLSTATE[42703]: Undefined column: 7 ERROR:  column "490" does not exist LINE 6:                   AND voucher_event.event_id = "490"                                                        ^ (SQL: SELECT merchantagreement.name, COUNT(voucher_event.id) as totalrefunds FROM voucher_event                   JOIN merchant ON merchant.id = voucher_event.merchant_id                   JOIN merchantagreement ON merchantagreement.merchant_id = merchant.id                   WHERE voucher_event.datetimecreated >= '2014-04-04'                   AND voucher_event.datetimecreated <= '2014-04-14'                   AND voucher_event.event_id = "490"                   GROUP BY merchantagreement.id) (Bindings: array ( ))' in /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php:556 Stack trace: #0 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), Object(Illuminate\Database\Query\Expression), Array) #1 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(277): Illuminate\Database\Connection->run(Object(Illuminate\Database\Query\Expression), Array, Object(Closure)) #2 [internal function]: Illuminate\Database\Connection->select(Object(Illuminate\Database\Query\Expression)) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(242): call_user_func_array(Array, Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(206): Illuminate\Database\DatabaseManager->__call('select', Array) #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(206): Illuminate\Database\DatabaseManager->select(Object(Illuminate\Database\Query\Expression)) #6 /var/www/arp_dev/app/controllers/admin/DashboardController.php(254): Illuminate\Support\Facades\Facade::__callStatic('select', Array) #7 /var/www/arp_dev/app/controllers/admin/DashboardController.php(254): Illuminate\Support\Facades\DB::select(Object(Illuminate\Database\Query\Expression)) #8 /var/www/arp_dev/app/controllers/admin/DashboardController.php(105): Controllers\Admin\DashboardController->getRefunds('2014-04-04', '2014-04-14') #9 [internal function]: Controllers\Admin\DashboardController->getIndex() #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #11 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #12 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #13 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #14 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #15 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #16 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #17 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #18 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #19 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #20 {main} [] []
[2014-04-14 11:37:08] log.ERROR: exception 'ErrorException' with message 'Undefined property: stdClass::$totalchb' in /var/www/arp_dev/app/controllers/admin/DashboardController.php:117 Stack trace: #0 /var/www/arp_dev/app/controllers/admin/DashboardController.php(117): Illuminate\Exception\Handler->handleError(8, 'Undefined prope...', '/var/www/arp_de...', 117, Array) #1 [internal function]: Controllers\Admin\DashboardController->getIndex() #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2014-04-14 11:54:16] log.ERROR: exception 'ErrorException' with message 'Undefined variable: transactions_amount' in /var/www/arp_dev/app/controllers/admin/DashboardController.php:108 Stack trace: #0 /var/www/arp_dev/app/controllers/admin/DashboardController.php(108): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/var/www/arp_de...', 108, Array) #1 [internal function]: Controllers\Admin\DashboardController->getIndex() #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2014-04-14 11:56:08] log.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in /var/www/arp_dev/app/controllers/admin/DashboardController.php:88 Stack trace: #0 /var/www/arp_dev/app/controllers/admin/DashboardController.php(88): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', '/var/www/arp_de...', 88, Array) #1 [internal function]: Controllers\Admin\DashboardController->getIndex() #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2014-04-14 12:12:29] log.ERROR: exception 'ErrorException' with message 'Undefined property: stdClass::$totaltransaction' in /var/www/arp_dev/app/controllers/admin/DashboardController.php:227 Stack trace: #0 /var/www/arp_dev/app/controllers/admin/DashboardController.php(227): Illuminate\Exception\Handler->handleError(8, 'Undefined prope...', '/var/www/arp_de...', 227, Array) #1 [internal function]: Controllers\Admin\DashboardController->getIndex() #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #7 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2014-04-14 13:53:17] log.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in /var/www/arp_dev/app/controllers/admin/InvoiceController.php:210 Stack trace: #0 /var/www/arp_dev/app/controllers/admin/InvoiceController.php(210): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', '/var/www/arp_de...', 210, Array) #1 /var/www/arp_dev/app/controllers/admin/InvoiceController.php(69): Controllers\Admin\MainvoiceController->generate() #2 [internal function]: Controllers\Admin\MainvoiceController->getIndex() #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #7 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #11 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #12 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #13 {main} [] []
[2014-04-14 13:53:31] log.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in /var/www/arp_dev/app/controllers/admin/InvoiceController.php:210 Stack trace: #0 /var/www/arp_dev/app/controllers/admin/InvoiceController.php(210): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', '/var/www/arp_de...', 210, Array) #1 /var/www/arp_dev/app/controllers/admin/InvoiceController.php(69): Controllers\Admin\MainvoiceController->generate() #2 [internal function]: Controllers\Admin\MainvoiceController->getIndex() #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #7 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #11 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #12 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #13 {main} [] []
[2014-04-14 13:54:30] log.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in /var/www/arp_dev/app/controllers/admin/InvoiceController.php:210 Stack trace: #0 /var/www/arp_dev/app/controllers/admin/InvoiceController.php(210): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', '/var/www/arp_de...', 210, Array) #1 /var/www/arp_dev/app/controllers/admin/InvoiceController.php(69): Controllers\Admin\MainvoiceController->generate() #2 [internal function]: Controllers\Admin\MainvoiceController->getIndex() #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #7 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #11 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #12 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #13 {main} [] []
[2014-04-14 13:54:36] log.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in /var/www/arp_dev/app/controllers/admin/InvoiceController.php:210 Stack trace: #0 /var/www/arp_dev/app/controllers/admin/InvoiceController.php(210): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', '/var/www/arp_de...', 210, Array) #1 /var/www/arp_dev/app/controllers/admin/InvoiceController.php(69): Controllers\Admin\MainvoiceController->generate() #2 [internal function]: Controllers\Admin\MainvoiceController->getIndex() #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #7 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #11 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #12 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #13 {main} [] []
[2014-04-14 14:12:12] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '=>' (T_DOUBLE_ARROW)' in /var/www/arp_dev/app/controllers/admin/DashboardController.php:199 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 14:31:34] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\Routing\UrlGenerator::back()' in /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:203 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-04-14 16:01:40] log.ERROR: exception 'ErrorException' with message 'Missing argument 3 for Controllers\Admin\DashboardController::getTransactionsamount(), called in /var/www/arp_dev/app/controllers/admin/DashboardController.php on line 103 and defined' in /var/www/arp_dev/app/controllers/admin/DashboardController.php:419 Stack trace: #0 /var/www/arp_dev/app/controllers/admin/DashboardController.php(419): Illuminate\Exception\Handler->handleError(2, 'Missing argumen...', '/var/www/arp_de...', 419, Array) #1 /var/www/arp_dev/app/controllers/admin/DashboardController.php(103): Controllers\Admin\DashboardController->getTransactionsamount('2014-04-04', '2014-04-14') #2 [internal function]: Controllers\Admin\DashboardController->getIndex() #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #7 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #11 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #12 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #13 {main} [] []
