[2014-03-26 09:19:09] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'ls' (T_STRING), expecting ';' or '{'' in /var/www/arp_dev/app/controllers/admin/MainvoiceController.php:66 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-03-26 09:41:42] log.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in /var/www/arp_dev/app/controllers/admin/MainvoiceController.php:723 Stack trace: #0 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(723): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', '/var/www/arp_de...', 723, Array) #1 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(230): Controllers\Admin\MainvoiceController->getTransactionRange(14, '2014-03-10 00:0...', '2014-03-20 23:5...') #2 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(69): Controllers\Admin\MainvoiceController->generate() #3 [internal function]: Controllers\Admin\MainvoiceController->getIndex() #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #6 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #7 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #11 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #12 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #13 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #14 {main} [] []
[2014-03-26 09:42:18] log.ERROR: exception 'ErrorException' with message 'Object of class Illuminate\Database\Eloquent\Builder could not be converted to string' in /var/www/arp_dev/app/controllers/admin/MainvoiceController.php:234 Stack trace: #0 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(234): Illuminate\Exception\Handler->handleError(4096, 'Object of class...', '/var/www/arp_de...', 234, Array) #1 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(69): Controllers\Admin\MainvoiceController->generate() #2 [internal function]: Controllers\Admin\MainvoiceController->getIndex() #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #7 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #11 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #12 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #13 {main} [] []
[2014-03-26 09:48:54] log.ERROR: exception 'PDOException' with message 'SQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for type character varying(10)' in /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php:353 Stack trace: #0 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(353): PDOStatement->execute(Array) #1 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\PostgresConnection), 'update "mainvoi...', Array) #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(356): Illuminate\Database\Connection->run('update "mainvoi...', Array, Object(Closure)) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(301): Illuminate\Database\Connection->affectingStatement('update "mainvoi...', Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1459): Illuminate\Database\Connection->update('update "mainvoi...', Array) #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(277): Illuminate\Database\Query\Builder->update(Array) #6 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(376): Illuminate\Database\Eloquent\Builder->update(Array) #7 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(69): Controllers\Admin\MainvoiceController->generate() #8 [internal function]: Controllers\Admin\MainvoiceController->getIndex() #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #11 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #12 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #13 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #14 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #15 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #16 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #17 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #18 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #19 {main} Next exception 'Exception' with message 'SQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for type character varying(10) (SQL: update "mainvoice" set "merchantagreement_id" = ?, "transactions_number" = ?, "transactions_amount" = ?, "transactions_avg" = ?, "transactionid_from" = ?, "transactionid_to" = ?, "redemptions_number" = ?, "redemptions_amount" = ?, "chargebacks_number" = ?, "chargebacks_amount" = ?, "refunds_number" = ?, "refunds_amount" = ?, "conversion_rate" = ?, "amount" = ?, "balance_out" = ?, "processcurrency" = ?, "updated_at" = ? where "id" = ?) (Bindings: array (   0 => 9,   1 => 2270,   2 => '303720.00',   3 => '133.7973568281938326',   4 => 218929,   5 => 225931,   6 => 1394,   7 => 171954,   8 => 40,   9 => -7029,   10 => 10,   11 => -1740,   12 => 1,   13 => 162237,   14 => 0,   15 =>    Voucherevent::__set_state(array(      'table' => 'voucher_event',      'timestamps' => true,      'connection' => NULL,      'primaryKey' => 'id',      'perPage' => 15,      'incrementing' => true,      'attributes' =>      array (       'currency' => 'USD',     ),      'original' =>      array (       'currency' => 'USD',     ),      'relations' =>      array (     ),      'hidden' =>      array (     ),      'visible' =>      array (     ),      'appends' =>      array (     ),      'fillable' =>      array (     ),      'guarded' =>      array (       0 => '*',     ),      'dates' =>      array (     ),      'touches' =>      array (     ),      'with' =>      array (     ),      'exists' => true,      'softDelete' => false,   )),   16 => '2014-03-26 09:48:54',   17 => 1021, ))' in /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php:556 Stack trace: #0 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'update "mainvoi...', Array) #1 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(356): Illuminate\Database\Connection->run('update "mainvoi...', Array, Object(Closure)) #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(301): Illuminate\Database\Connection->affectingStatement('update "mainvoi...', Array) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1459): Illuminate\Database\Connection->update('update "mainvoi...', Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(277): Illuminate\Database\Query\Builder->update(Array) #5 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(376): Illuminate\Database\Eloquent\Builder->update(Array) #6 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(69): Controllers\Admin\MainvoiceController->generate() #7 [internal function]: Controllers\Admin\MainvoiceController->getIndex() #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #12 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #13 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #14 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #15 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #16 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #17 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #18 {main} [] []
[2014-03-26 09:52:28] log.ERROR: exception 'PDOException' with message 'SQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for type character varying(10)' in /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php:353 Stack trace: #0 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(353): PDOStatement->execute(Array) #1 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\PostgresConnection), 'update "mainvoi...', Array) #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(356): Illuminate\Database\Connection->run('update "mainvoi...', Array, Object(Closure)) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(301): Illuminate\Database\Connection->affectingStatement('update "mainvoi...', Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1459): Illuminate\Database\Connection->update('update "mainvoi...', Array) #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(277): Illuminate\Database\Query\Builder->update(Array) #6 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(376): Illuminate\Database\Eloquent\Builder->update(Array) #7 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(69): Controllers\Admin\MainvoiceController->generate() #8 [internal function]: Controllers\Admin\MainvoiceController->getIndex() #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #11 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #12 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #13 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #14 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #15 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #16 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #17 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #18 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #19 {main} Next exception 'Exception' with message 'SQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for type character varying(10) (SQL: update "mainvoice" set "merchantagreement_id" = ?, "transactions_number" = ?, "transactions_amount" = ?, "transactions_avg" = ?, "transactionid_from" = ?, "transactionid_to" = ?, "redemptions_number" = ?, "redemptions_amount" = ?, "chargebacks_number" = ?, "chargebacks_amount" = ?, "refunds_number" = ?, "refunds_amount" = ?, "conversion_rate" = ?, "amount" = ?, "balance_out" = ?, "processcurrency" = ?, "updated_at" = ? where "id" = ?) (Bindings: array (   0 => 9,   1 => 2270,   2 => '303720.00',   3 => '133.7973568281938326',   4 => 218929,   5 => 225931,   6 => 1394,   7 => 171954,   8 => 40,   9 => -7029,   10 => 10,   11 => -1740,   12 => 1,   13 => 162237,   14 => 0,   15 =>    Voucherevent::__set_state(array(      'table' => 'voucher_event',      'timestamps' => true,      'connection' => NULL,      'primaryKey' => 'id',      'perPage' => 15,      'incrementing' => true,      'attributes' =>      array (       'currency' => 'USD',     ),      'original' =>      array (       'currency' => 'USD',     ),      'relations' =>      array (     ),      'hidden' =>      array (     ),      'visible' =>      array (     ),      'appends' =>      array (     ),      'fillable' =>      array (     ),      'guarded' =>      array (       0 => '*',     ),      'dates' =>      array (     ),      'touches' =>      array (     ),      'with' =>      array (     ),      'exists' => true,      'softDelete' => false,   )),   16 => '2014-03-26 09:52:28',   17 => 1021, ))' in /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php:556 Stack trace: #0 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'update "mainvoi...', Array) #1 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(356): Illuminate\Database\Connection->run('update "mainvoi...', Array, Object(Closure)) #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(301): Illuminate\Database\Connection->affectingStatement('update "mainvoi...', Array) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1459): Illuminate\Database\Connection->update('update "mainvoi...', Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(277): Illuminate\Database\Query\Builder->update(Array) #5 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(376): Illuminate\Database\Eloquent\Builder->update(Array) #6 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(69): Controllers\Admin\MainvoiceController->generate() #7 [internal function]: Controllers\Admin\MainvoiceController->getIndex() #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #12 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #13 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #14 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #15 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #16 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #17 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #18 {main} [] []
[2014-03-26 09:55:24] log.ERROR: exception 'PDOException' with message 'SQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for type character varying(10)' in /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php:353 Stack trace: #0 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(353): PDOStatement->execute(Array) #1 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\PostgresConnection), 'update "mainvoi...', Array) #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(356): Illuminate\Database\Connection->run('update "mainvoi...', Array, Object(Closure)) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(301): Illuminate\Database\Connection->affectingStatement('update "mainvoi...', Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1459): Illuminate\Database\Connection->update('update "mainvoi...', Array) #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(277): Illuminate\Database\Query\Builder->update(Array) #6 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(376): Illuminate\Database\Eloquent\Builder->update(Array) #7 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(69): Controllers\Admin\MainvoiceController->generate() #8 [internal function]: Controllers\Admin\MainvoiceController->getIndex() #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #11 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #12 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #13 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #14 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #15 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #16 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #17 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #18 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #19 {main} Next exception 'Exception' with message 'SQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for type character varying(10) (SQL: update "mainvoice" set "merchantagreement_id" = ?, "transactions_number" = ?, "transactions_amount" = ?, "transactions_avg" = ?, "transactionid_from" = ?, "transactionid_to" = ?, "redemptions_number" = ?, "redemptions_amount" = ?, "chargebacks_number" = ?, "chargebacks_amount" = ?, "refunds_number" = ?, "refunds_amount" = ?, "conversion_rate" = ?, "amount" = ?, "balance_out" = ?, "processcurrency" = ?, "updated_at" = ? where "id" = ?) (Bindings: array (   0 => 9,   1 => 2270,   2 => '303720.00',   3 => '133.7973568281938326',   4 => 218929,   5 => 225931,   6 => 1394,   7 => 171954,   8 => 40,   9 => -7029,   10 => 10,   11 => -1740,   12 => 1,   13 => 162237,   14 => 0,   15 =>    Voucherevent::__set_state(array(      'table' => 'voucher_event',      'timestamps' => true,      'connection' => NULL,      'primaryKey' => 'id',      'perPage' => 15,      'incrementing' => true,      'attributes' =>      array (       'currency' => 'USD',     ),      'original' =>      array (       'currency' => 'USD',     ),      'relations' =>      array (     ),      'hidden' =>      array (     ),      'visible' =>      array (     ),      'appends' =>      array (     ),      'fillable' =>      array (     ),      'guarded' =>      array (       0 => '*',     ),      'dates' =>      array (     ),      'touches' =>      array (     ),      'with' =>      array (     ),      'exists' => true,      'softDelete' => false,   )),   16 => '2014-03-26 09:55:24',   17 => 1021, ))' in /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php:556 Stack trace: #0 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'update "mainvoi...', Array) #1 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(356): Illuminate\Database\Connection->run('update "mainvoi...', Array, Object(Closure)) #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(301): Illuminate\Database\Connection->affectingStatement('update "mainvoi...', Array) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1459): Illuminate\Database\Connection->update('update "mainvoi...', Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(277): Illuminate\Database\Query\Builder->update(Array) #5 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(376): Illuminate\Database\Eloquent\Builder->update(Array) #6 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(69): Controllers\Admin\MainvoiceController->generate() #7 [internal function]: Controllers\Admin\MainvoiceController->getIndex() #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #12 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #13 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #14 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #15 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #16 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #17 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #18 {main} [] []
[2014-03-26 09:56:18] log.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in /var/www/arp_dev/app/controllers/admin/MainvoiceController.php:734 Stack trace: #0 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(734): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', '/var/www/arp_de...', 734, Array) #1 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(230): Controllers\Admin\MainvoiceController->getTransactionRange(14, '2014-03-10 00:0...', '2014-03-20 23:5...') #2 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(69): Controllers\Admin\MainvoiceController->generate() #3 [internal function]: Controllers\Admin\MainvoiceController->getIndex() #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #6 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #7 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #11 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #12 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #13 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #14 {main} [] []
[2014-03-26 09:57:36] log.ERROR: exception 'ErrorException' with message 'Invalid argument supplied for foreach()' in /var/www/arp_dev/app/controllers/admin/MainvoiceController.php:726 Stack trace: #0 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(726): Illuminate\Exception\Handler->handleError(2, 'Invalid argumen...', '/var/www/arp_de...', 726, Array) #1 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(230): Controllers\Admin\MainvoiceController->getTransactionRange(14, '2014-03-10 00:0...', '2014-03-20 23:5...') #2 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(69): Controllers\Admin\MainvoiceController->generate() #3 [internal function]: Controllers\Admin\MainvoiceController->getIndex() #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #6 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #7 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #11 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #12 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #13 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #14 {main} [] []
[2014-03-26 09:58:49] log.ERROR: exception 'ErrorException' with message 'Undefined variable: pc' in /var/www/arp_dev/app/controllers/admin/MainvoiceController.php:728 Stack trace: #0 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(728): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/var/www/arp_de...', 728, Array) #1 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(230): Controllers\Admin\MainvoiceController->getTransactionRange(14, '2014-03-10 00:0...', '2014-03-20 23:5...') #2 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(69): Controllers\Admin\MainvoiceController->generate() #3 [internal function]: Controllers\Admin\MainvoiceController->getIndex() #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #6 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #7 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #11 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #12 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #13 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #14 {main} [] []
[2014-03-26 09:58:57] log.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in /var/www/arp_dev/app/controllers/admin/MainvoiceController.php:728 Stack trace: #0 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(728): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', '/var/www/arp_de...', 728, Array) #1 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(230): Controllers\Admin\MainvoiceController->getTransactionRange(14, '2014-03-10 00:0...', '2014-03-20 23:5...') #2 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(69): Controllers\Admin\MainvoiceController->generate() #3 [internal function]: Controllers\Admin\MainvoiceController->getIndex() #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #6 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #7 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #11 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #12 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #13 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #14 {main} [] []
[2014-03-26 09:59:47] log.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in /var/www/arp_dev/app/controllers/admin/MainvoiceController.php:735 Stack trace: #0 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(735): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', '/var/www/arp_de...', 735, Array) #1 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(230): Controllers\Admin\MainvoiceController->getTransactionRange(14, '2014-03-10 00:0...', '2014-03-20 23:5...') #2 /var/www/arp_dev/app/controllers/admin/MainvoiceController.php(69): Controllers\Admin\MainvoiceController->generate() #3 [internal function]: Controllers\Admin\MainvoiceController->getIndex() #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getIndex', Array) #6 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #7 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #11 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #12 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #13 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #14 {main} [] []
[2014-03-26 11:20:07] log.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in /var/www/arp_dev/app/storage/views/2d8971310e59d66b3c8ffc54892f57e2:74 Stack trace: #0 /var/www/arp_dev/app/storage/views/2d8971310e59d66b3c8ffc54892f57e2(74): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', '/var/www/arp_de...', 74, Array) #1 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(38): include('/var/www/arp_de...') #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/arp_de...', Array) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/View/View.php(100): Illuminate\View\Engines\CompilerEngine->get('/var/www/arp_de...', Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/View/View.php(81): Illuminate\View\View->getContents() #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Http/Response.php(70): Illuminate\View\View->render() #6 /var/www/arp_dev/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(141): Illuminate\Http\Response->setContent(Object(Illuminate\View\View)) #7 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1414): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View)) #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request)) #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'getShow', Object(Illuminate\View\View)) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getShow', Array) #11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('1024') #12 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #13 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #14 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #15 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #16 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #17 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #18 {main} [] []
[2014-03-26 11:24:00] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined function f()' in /var/www/arp_dev/app/storage/views/2d8971310e59d66b3c8ffc54892f57e2:75 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main} [] []
[2014-03-26 11:24:22] log.ERROR: exception 'ErrorException' with message 'Use of undefined constant disabled - assumed 'disabled'' in /var/www/arp_dev/app/storage/views/2d8971310e59d66b3c8ffc54892f57e2:75 Stack trace: #0 /var/www/arp_dev/app/storage/views/2d8971310e59d66b3c8ffc54892f57e2(75): Illuminate\Exception\Handler->handleError(8, 'Use of undefine...', '/var/www/arp_de...', 75, Array) #1 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(38): include('/var/www/arp_de...') #2 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/arp_de...', Array) #3 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/View/View.php(100): Illuminate\View\Engines\CompilerEngine->get('/var/www/arp_de...', Array) #4 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/View/View.php(81): Illuminate\View\View->getContents() #5 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Http/Response.php(70): Illuminate\View\View->render() #6 /var/www/arp_dev/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(141): Illuminate\Http\Response->setContent(Object(Illuminate\View\View)) #7 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1414): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View)) #8 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request)) #9 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'getShow', Object(Illuminate\View\View)) #10 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getShow', Array) #11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('1022') #12 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #13 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #14 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #15 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #16 /var/www/arp_dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #17 /var/www/arp_dev/public/index.php(49): Illuminate\Foundation\Application->run() #18 {main} [] []
